DemoApp-EntityFramework/DemoAppMockData/Models/Agents.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DemoAppMockData.Models
{
    public class Agents
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ShortDescription { get; set; }
        public string LongDescription { get; set; }
        public string ContactNumber { get; set; }
        public string NumberOfDeals { get; set; }
        public string ImageUrl { get; set; }
        public string ImageThumbnailUrl { get; set; }
        public int Rating { get; set; }
        public int NumberOfReviews { get; set; }
    }
}

DemoApp-EntityFramework/DemoAppMockData/Controllers/AgentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DemoAppMockData.Models;
using DemoAppMockData.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace DemoAppMockData.Controllers
{
    public class AgentsController : Controller
    {
        private readonly IAgentRepository _agentRepository;

        public AgentsController(IAgentRepository agentrepository)
        {
            _agentRepository = agentrepository;
        }
        public IActionResult Index()
        {
            return View();
        }

        public ViewResult List()
        {
            AgentsListViewModel agentsListViewModel = new AgentsListViewModel();
            agentsListViewModel.agents = _agentRepository.AllAgent;
            agentsListViewModel.CurrentAgency = "SantJust Agents";
            return View(agentsListViewModel);
        }

        public IActionResult AgentDetails(int id)
        {
            var agent = _agentRepository.GetAgentById(id);
            if (agent == null)
                return NotFound();

            return View(agent);
        }
    }
}

DemoApp-EntityFramework/DemoAppMockData/Views/Shared/_Agent.cshtml
@model Agents

<div class="col-sm-3 col-lg-3 col-md-3">
    <div class="thumbnail">
        <img src="@Model.ImageThumbnailUrl" alt="">
        <div class="caption">

            <h3>
                <a asp-controller="Agents" asp-action="AgentDetails" asp-route-id="@Model.Id">@Model.Name</a>

            </h3>
            <p><i style="font-size:18px" class="fa">&#xf095;</i> &nbsp;  @Model.ContactNumber</p>
            <p>

                @for (int i = 0; i < (Model.Rating); i++)
                {
                    <span class="fa fa-star checked"></span>
                }

                @Model.Rating Stars | @Model.NumberOfReviews.ToString() Reviews
            </p>

            <p style="background-color:lightgray">@Model.LongDescription</p>
        </div>
    </div>
</div>

DemoApp-EntityFramework/DemoAppMockData/Views/Shared/_Carousel.cshtml
<div class="row carousel-holder">
    <div class="col-md-12">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="item active">
                    <img class="slide-image" src="~/Images/SantJust.jpg" alt="">

                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/atlas.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/europiri.jpg" alt="">
                </div>
            </div>
            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>
    </div>
</div>

DemoApp-EntityFramework/DemoAppMockData/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro">
    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    <link href="~/Content/site.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


</head>
<body>
    <div class="container">
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                        <li><a asp-controller="Agents" asp-action="List">Agents</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="row">
            <div class="col-md-3">
                <p class="lead">
                    <img class="img-responsive" alt="BotObi'" src="~/Images/Logo.JPG" />
                </p>
            </div>
            <div class="col-md-9">
                @RenderBody()
            </div>
        </div>
    </div>
</body>
</html>